name: Test Coding JSON

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: DRY_RUN rake generate_coding_json
        run: |
          DRY_RUN=true rake generate_coding_json
